### ISSUE TITLE
Typing improvements

### ISSUE THREAD

**Issue by StireArLankar** [christianalfoni/react-states#2]
Hello and thanks for your hard work! Your libraries help me with learning the right way of doing with state management.

So i want to suggest some typing improvements:

1. Extract typing for first argument in `useStates`
~~~ts
...
export type UseStatesReducer<C extends TContext, A extends TAction> = {
    [State in C['state']]: {
      [Type in A['type']]?: (
        action: A extends { type: Type } ? A : never,
        state: C extends { state: State } ? C : never,
      ) => C extends { state: C['state'] } ? C : never;
    }
}

export const useStates = <C extends TContext, A extends TAction>(
  transitions: UseStatesReducer<C, A>,
  initialState: C,
) => {
...
~~~

2. Add return type not only to `useMemo`, but also to `useStates`
Somehow my vscode decided to return `any` 2 times in 10 minutes and after adding such typing it calmed down
~~~ts
...
export const useStates = <C extends TContext, A extends TAction>(
  transitions: UseStatesReducer<C, A>,
  initialState: C,
): States<C, A> => {
...
~~~

3. Add generic return to `transform` functions 
~~~ts
...
export type TTransforms<C extends TContext, R = any> =
  | C['state']
  | {
      [State in C['state']]: ( // [State in C['state']]?: (
        state: C extends { state: State } ? C : never
      ) => R // or R | null if ? mark is present
    }
...
export interface States<Context extends TContext, Action extends TAction> {
  context: Context
  dispatch: React.Dispatch<Action>
  exec: (effects: TEffects<Context>) => void | (() => void)
  transform: <R = any>(transforms: TTransforms<Context, R>) => R // R | null
...
export const transform = <C extends TContext, R = any>(
  state: C,
  transforms: TTransforms<C, R>
  // @ts-ignore
): R => (transforms[state.state] ? transforms[state.state](state) : null) // R | null
...
~~~

i see `transform` function as prettier version of switch, so having correct types for return values should be good idea

also i am not sure why there is `?` mark in `TTransforms`, wouldn't exhaustive check be better?
~~~ts
[State in C["state"]]?: (
~~~

adding exhaustive version of `transform` might be another solution
~~~ts
...
export type TTransforms<C extends TContext, R = any> =
  | C['state']
  | {
      [State in C['state']]?: (
        state: C extends { state: State } ? C : never
      ) => R | null
    }
    
export type TExhaustiveTransforms<C extends TContext, R = any> =
  | C['state']
  | {
      [State in C['state']]: (
        state: C extends { state: State } ? C : never
      ) => R
    }
...
~~~

5. I am not really sure about why entries of `exec` should accept arrays
~~~ts
SOME_STATE: [function effectA(currentState) {}, function effectB(currentState) {}]
~~~
could just be
~~~ts
SOME_STATE: (currentState) => {
  const clear1 = effectA(currentState)
  const clear2 = effectA(currentState)
  
  return () => {
    clear1()
    clear2()
  }
}
~~~
(or maybe im just bad with logic and dont really understand how this works)
~~~ts
effects[state.state].reduce((dispose, effect) => {
  const result = effect(state)

  return () => {
    if (dispose) {
      dispose()
    }
    if (result) {
      result()
    }
  }
}, undefined)
~~~
6. If `usableState.exec` effects must run only on state field changes, then
~~~ts
  useEffect(
    () =>
      list.exec({
        LOADING: () => {
          axios
            .get('/list')
            .then(response => {
              listDispatch({ type: 'FETCH_SUCCESS', data: response.data });
            })
            .catch(error => {
              listDispatch({ type: 'FETCH_ERROR', error: error.message });
            });
        },
      }),
    [list],
  );
~~~
will surely break if `LOADING` state accepts actions that let it stay in `LOADING` state, but changes actual state object
to ensure that effects will run **only** on state field change they could be moved to arguments of useState
~~~ts
...
const someState = useStates(reducer, initialState, effects)
...
~~~

~~~ts
...
export const useStates = <C extends TContext, A extends TAction>(
  transitions: UseStatesReducer<C, A>,
  initialState: C,
  effects: TEffects<C> = {}
): States<C, A> => {
  const reducer = React.useReducer(
    (state: C, action: A) => transition(state, action, transitions),
    initialState
  )

  const effectsRef = React.useRef(effects)
  effectsRef.current = effects

  React.useEffect(() => {
    return exec(reducer[0], effectsRef.current)
  }, [reducer[0].state])
...
~~~
I am not really sure if `ref` trick is needed tho, you are already breaking `react-hooks/exhaustive-deps` eslint rule at `useMemo` and not doing same trick with `reducer[0]` violates this rule in `useEffect`

**Comment by christianalfoni** [comment]
Hi @StireArLankar and thanks so much for taking the time to dive into this! 😄 Let me give you some feedback:

1. Jup, agreed! Think I'll call it `UseStatesTransitions`, just for consistency, but yeah. Cleans up!
2. Ah, interesting, jup... does not hurt to add it there 👍 
3. Yeah, generic return definitely makes sense! In practice I am not sure how much value it gives, but it is more correct indeed 👍 😄 
4. In my experience you do not always want to transform every single state, but I do see the point of being explicit about it. As it ensures that you do not get any unwanted "nothing that renders". So even having to explicitly do `{ SOME_STATE: () => null }` is more predictable. Yeah, lets change that as well
5. This array thing was a bit of a whim. The intention was to be able to more easily re-use effects, like:

```ts
exec(context, {
  SOME_STATE: [track, () => {}]
})
```

But you can achieve the same with functional composition:

```ts
exec(context, {
  SOME_STATE: track(() => {})
})
```

So reducing the API surface for "edge cases" is always a good thing. Lets remove arrays, as you can solve this in other ways no matter 😄 

6. On this last point the idea is to be able to choose by using the `useEffect` dependencies array. So by default it works as you say. Every time you move into a new context, even though the state is the same, the `exec` will run:

```ts
 useEffect(
    () =>
      list.exec({
        LOADING: () => {
          axios
            .get('/list')
            .then(response => {
              listDispatch({ type: 'FETCH_SUCCESS', data: response.data });
            })
            .catch(error => {
              listDispatch({ type: 'FETCH_ERROR', error: error.message });
            });
        },
      }),
    [list],
  );
```

But you can just change the dependencies array:

```ts
 useEffect(
    () =>
      list.exec({
        LOADING: () => {
          axios
            .get('/list')
            .then(response => {
              listDispatch({ type: 'FETCH_SUCCESS', data: response.data });
            })
            .catch(error => {
              listDispatch({ type: 'FETCH_ERROR', error: error.message });
            });
        },
      }),
     // Just point to the actual state and it only runs when the actual state changes
    [list.context.state],
  );
```

Does that make sense? 😄 Should probably highlight this in the docs.

Please give me your feedback and I can prepare a new release with your suggestions 😍

**Comment by StireArLankar** [comment]
Hello @christianalfoni.

3-4. With generic as returned value and exhaustive check writing something like
```tsx
const stringOrJSXElementOrNull = state.transform({
  NOT_LOADED: () => 'Not loaded',
  LOADING: () => 'Loading...',
  LOADED: ({ data }) => (
    <ul>
      {data.map(todo => (
        <li>{todo.title}</li>
      ))}
    </ul>
  ),
  ERROR: ({ error }) => error.message,
  NULLISH_STATE: () => null
})
```
will result in `Type 'Element' is not assignable to type 'string'` on line with `LOADED` and same (but with `null`) on `NULLISH_STATE`, so docs should mention how to bypass this:
```tsx
const stringOrJSXElementOrNull = state.transform<string | JSX.Element | null>({ // or just <React.ReactNode>
  NOT_LOADED: () => 'Not loaded',
  LOADING: () => 'Loading...',
  LOADED: ({ data }) => (
    <ul>
      {data.map(todo => (
        <li>{todo.title}</li>
      ))}
    </ul>
  ),
  ERROR: ({ error }) => error.message,
  NULLISH_STATE: () => null
})
```
Everything else seems reasonable!

**Comment by christianalfoni** [comment]
Okay, so I have a new release out, 2.0.0. I did some black magic for the last thing you mentioned here, so you do not have to explicitly type the return type, it is inferred :)

Let me know if I missed something!
