### ISSUE TITLE
Should react and react-dom be peer dependencies?

### ISSUE THREAD

**Issue by allforabit** [christianalfoni/react-states#3]
I just had a weird error because I'm on React 17.01. I was able to fix this by upgrading to the version that react-states is on. I think normally libs list react and react-dom as peer dependencies to allow some flexibility with the version of react?

**Comment by christianalfoni** [comment]
It does not actually depend on `react-dom`, but I moved `react´ as peer dependency and removed all dependencies, cause it really does not have any. Let's see if it works 😄

**Comment by allforabit** [comment]
Wow great thanks!
