### ISSUE TITLE
Should `tslib` be a hard dependency?

### ISSUE THREAD

**Issue by nunofmaia** [christianalfoni/react-states#4]
_Before I get to the point, let me say that I really enjoyed seeing you coming up with the idea for this library and using it to build the Excalidraw app._ 🙇 

I started using `react-states` in an application and now I'm having some issues building it. Currently, `tslib` is listed as a `devDependency` but the CommonJS bundle requires it. This is only an issue because I'm setting `NODE_ENV=production` and `devDependencies` are not installed.

Should `tslib` be moved to the dependencies list?

**Comment by christianalfoni** [comment]
You still have this issue now with `6.x.x`? 😄 

So sorry for late response here, but the library was considered "in development" up until now.

**Comment by nunofmaia** [comment]
No problem, thanks for taking the time to comment on this after all this time. 🙏  

We ended up replacing the library with a different solution and I'm not currently using it on other projects.
Great to know that the library is in a more stable state now, will definitely check it out again when I get the chance.

In the meantime, I believe we can close the issue. Thanks again!

**Comment by christianalfoni** [comment]
So this library just got another iteration based experiences and later TypeScript versions
