### ISSUE TITLE
Making context type declaration less verbose

### ISSUE THREAD

**Issue by FWeinb** [christianalfoni/react-states#5]
I am really enjoying this library and the associated architecture that comes with this.

Just some food for though here, assuming we have this context type:
```ts
type Context =
  | {
      state: 'LOADING';
    }
  | {
      state: 'LOADED';
      data: [];
    }
  | {
      state: 'ERROR';
      error: string;
    };
```
I do find the type declaration for the context type a little bit verbose and it leaks implementation details (e.g. `state` key name). I propose to write this type like this:
```ts
type Context = {
	LOADING: {},
	LOADED: { data: [] },
	ERROR: { error: string }
}
```
To focus on the important bits; state name and custom data that is associated with that state. 

All this can be done in userland without modifications to react-states by using a custom generic type factory like this:
```ts
type Expand<T> = T extends infer U ? { [K in keyof U]: U[K] } : never
type CreateUnion<T extends { [key: string]: any }> = { [K in keyof T]: Expand<{ state: K; } & T[K]> }[keyof T] 
``` 
usage would look like this
```ts
type Context = CreateUnion<{
	LOADING: {},
	LOADED: { data: [] },
	ERROR: { error: string }
}>
```

You can find a [ts playground](https://www.typescriptlang.org/play?ts=4.3.5&ssl=9&ssc=1&pln=4&pc=1#code/C4TwDgpgBAogHmAhgOwCYB4AqA+KBeKTKCOYCNAZygEtkAzCAJygFUoB+KAbygG0BpGsigBrCCAD2dVgF0AXKwEyoAXygLkEAG5MAUKEhQAwowiIyLZNQnIsxUuVRUevMSAUVgjWgHN5UFBBVXAIXQVpRcSlCf3gkNHQeT3MIBX4AblUoADJCJVwVVyjpTGVdfXBoIxsyUnxjUxTLa1suXQBIABkAeQBBABEASQA5AHEFLhUAGg6egZh+iahUc0QFXmVpjpgAJR3unaWmRglGDy9fVV0VbHLdIA) to experiment with this.

What do you think about this, react-states could even use that type factory internally to allow writing these type like this by default?

**Comment by christianalfoni** [comment]
Extremely late answer to this 😂 

This is really cool! I have been back and forth on the level of abstraction, and decided to be as close to what people already do... but! We do have type helpers like `PickState`, so one could argue that this is on the same abstraction level 🤔 

One thing though is that if you first do this for state, you would probably want to do it for actions and commands as well. Again, we have `PickAction` and `PickCommand` ... so similar type  helpers to create the unions could definitely be a think.

```ts
type State = StateUnion<>
type Action = ActionUnion<>
type Command = CommandUnion<>
```

Any other suggestions on names?

**Comment by christianalfoni** [comment]
So did another iteration here after some experiences using it and also newer TypeScript versions 😄
